import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { Installer } from './src/installer.js';
import { ConnectorAgent } from './src/agent.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const CLOUD_URL = 'http://localhost:5001';
const FRESH_MACHINE_DIR = path.resolve(__dirname, '../scratch/fresh_machine_simulation');

async function runFreshMachineSimulation() {
  console.log('================================================================');
  console.log('🖥️ PHASE 1 STEP 5: FRESH MACHINE INSTALLATION & LIFECYCLE TEST');
  console.log('================================================================\n');

  // Prepare clean isolated "customer PC" workspace
  if (fs.existsSync(FRESH_MACHINE_DIR)) {
    fs.rmSync(FRESH_MACHINE_DIR, { recursive: true, force: true });
  }
  fs.mkdirSync(FRESH_MACHINE_DIR, { recursive: true });
  console.log(`Isolated customer environment created at:\n  ${FRESH_MACHINE_DIR}\n`);

  // -------------------------------------------------------------
  // Step 1: Cloud provisions a new Beta Tenant and Connector Token
  // -------------------------------------------------------------
  console.log('--- Step 1: Cloud Provisions Tenant & Generates Token ---');
  
  // 1. Create Tenant
  const tenantRes = await fetch(`${CLOUD_URL}/api/tenants`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ companyName: 'Omega Manufacturing Industries Ltd' })
  });
  const tenantData = await tenantRes.json();
  const tenant = tenantData.tenant;
  console.log(`  ✔ Tenant Created: "${tenant.companyName}" (ID: ${tenant.id})`);

  // 2. Provision Connector
  const connectorId = `conn_omega_pune_${Date.now().toString().slice(-4)}`;
  const connRes = await fetch(`${CLOUD_URL}/api/tenants/${tenant.id}/connectors`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ connectorId })
  });
  const connData = await connRes.json();
  console.log(`  ✔ Connector Provisioned: ${connData.connectorId}`);
  console.log(`  ✔ One-time Secret Token: ${connData.token.slice(0, 16)}...`);

  // -------------------------------------------------------------
  // Step 2: Customer runs Setup Wizard (Install -> Configure -> Validate)
  // -------------------------------------------------------------
  console.log('\n--- Step 2: Executing Setup Wizard on Fresh Machine ---');
  const installer = new Installer({
    targetDir: FRESH_MACHINE_DIR,
    interactive: false
  });

  const installResult = await installer.run({
    cloudUrl: CLOUD_URL,
    connectorId: connData.connectorId,
    secret: connData.token,
    tallyHost: '127.0.0.1',
    tallyPort: 9000,
    startAgent: false // We will control agent lifecycle explicitly
  });

  if (!installResult.success) {
    throw new Error('Installer execution failed');
  }

  // Verify created files
  const configPath = path.join(FRESH_MACHINE_DIR, 'config.json');
  const logsDir = path.join(FRESH_MACHINE_DIR, 'logs');
  if (!fs.existsSync(configPath)) throw new Error('config.json not generated by installer');
  if (!fs.existsSync(logsDir)) throw new Error('logs/ directory not created by installer');

  console.log(`  ✔ Configuration verified on disk: ${configPath}`);
  console.log(`  ✔ Config contents:`, JSON.parse(fs.readFileSync(configPath, 'utf-8')));

  // -------------------------------------------------------------
  // Step 3: Start Standalone Background Agent Daemon
  // -------------------------------------------------------------
  console.log('\n--- Step 3: Launching Standalone Background Agent Daemon ---');
  const agent = new ConnectorAgent(configPath);
  await agent.start();

  console.log('Waiting 3 seconds for initial telemetry and registration to settle...');
  await new Promise(r => setTimeout(r, 3000));

  // -------------------------------------------------------------
  // Step 4: Verify Cloud Connection & Heartbeat
  // -------------------------------------------------------------
  console.log('\n--- Step 4: Verifying Cloud Status & Heartbeat Delivery ---');
  const psqlCheckRes = await fetch(`${CLOUD_URL}/api/connector/status`);
  const serverStatus = await psqlCheckRes.json();
  console.log('Cloud Telemetry Status:', {
    agentId: serverStatus.agentId,
    status: serverStatus.status,
    tallyConnection: serverStatus.tallyConnectionStatus,
    activeCompany: serverStatus.activeCompany,
    lastHeartbeat: serverStatus.lastHeartbeat
  });

  if (serverStatus.status !== 'ONLINE') {
    throw new Error(`Expected server status ONLINE, got ${serverStatus.status}`);
  }

  // -------------------------------------------------------------
  // Step 5: Execute Export Job in Background
  // -------------------------------------------------------------
  console.log('\n--- Step 5: Dispatching Export Job to Fresh Machine Agent ---');
  const jobCreateRes = await fetch(`${CLOUD_URL}/api/connector/jobs/create`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      tenantId: tenant.id,
      connectorId: connData.connectorId,
      dataset: 'CHART_OF_ACCOUNTS'
    })
  });
  const createdJob = (await jobCreateRes.json()).job;
  console.log(`  ✔ Cloud created job: ${createdJob.id} (${createdJob.dataset})`);

  console.log('Triggering agent poll...');
  await agent.jobProcessor.pollOnce();

  // Verify job reached COMPLETED
  const jobStatusRes = await fetch(`${CLOUD_URL}/api/exports/${createdJob.id}`);
  const finalJob = await jobStatusRes.json();
  console.log(`  ✔ Job Execution Complete: Status = ${finalJob.status}, Rows = ${finalJob.rowCount}, File = "${finalJob.filename}"`);
  if (finalJob.status !== 'COMPLETED') throw new Error(`Job status was not COMPLETED: ${finalJob.status}`);

  // -------------------------------------------------------------
  // Step 6: Verify Local Disk Logs
  // -------------------------------------------------------------
  console.log('\n--- Step 6: Verifying Local Disk Logs on Fresh Machine ---');
  const agentLogPath = path.join(process.cwd(), 'logs', 'agent.log');
  const errorLogPath = path.join(process.cwd(), 'logs', 'errors.log');

  if (fs.existsSync(agentLogPath)) {
    const logContent = fs.readFileSync(agentLogPath, 'utf-8');
    const logLines = logContent.trim().split('\n');
    console.log(`  ✔ logs/agent.log verified (${logLines.length} entries recorded)`);
    console.log(`  Recent log line: ${logLines[logLines.length - 1]}`);
  } else {
    console.warn('  ⚠ agent.log not found at expected path');
  }

  // -------------------------------------------------------------
  // Step 7: Clean Shutdown
  // -------------------------------------------------------------
  console.log('\n--- Step 7: Graceful Daemon Shutdown ---');
  agent.stop();
  console.log('  ✔ Standalone agent daemon stopped cleanly.');

  console.log('\n================================================================');
  console.log('🎉 FRESH MACHINE SIMULATION VALIDATION COMPLETED SUCCESSFULLY!');
  console.log('================================================================\n');
}

runFreshMachineSimulation().catch(err => {
  console.error('\n✖ FRESH MACHINE SIMULATION FAILED:', err);
  process.exit(1);
});
